---
language: python
services: docker

env:
  global:
    - ROLE_NAME: postgresql
  matrix:
    - MOLECULE_DISTRO: centos7

install:
  # Install test dependencies
  - pip install docker ansible-lint "molecule>=3,<4" testinfra

env:
  - SCENARIO=default
  - SCENARIO=config
  - SCENARIO=ramdisk

script:
  # Run tests
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
