---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-postgresql
      vars:
        pg_stat_tmp_on_ram_disk: true
        pg_databases:
          - name: acme
            owner: "{{ pg_superuser }}"
