---
- name: Stop postgresql
  service:
    name: "{{ pg_service }}"
    state: stopped

- name: Remove old PostgreSQL cluster directory
  file:
    path: "{{ pg_data_dir }}/"
    state: absent

- name: Create PostgreSQL data directory
  file:
    path: "{{ pg_data_dir }}"
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    mode: 0700
    state: directory

- name: Check if cluster directory exists
  stat:
    path: "{{ pg_data_dir }}"
  register: pg_data_dir_stat

- name: Clone cluster directory of master
  command: |
    pg_basebackup -c fast -X stream -R \
                  -h {{ pg_master_ip }} \
                  -p {{ pg_port }} \
                  -U {{ pg_replication_user }} \
                  -D {{ pg_data_dir }}
  become: true
  become_user: "{{ pg_user }}"
  when: pg_data_dir_stat.stat.exists

- name: Set cluster ownership
  file:
    path: "{{ pg_data_dir }}"
    state: directory
    recurse: true
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"

- name: Start enable postgresql
  service:
    name: "{{ pg_service }}"
    state: started
    enabled: "{{ pg_service_enabled }}"
