---
- name: create systemd override directory for postgresql-12
  file:
    path: /etc/systemd/system/postgresql-12.service.d
    state: directory
- name: create file
  template:
    src: templates/systemd.override.conf.j2
    dest: /etc/systemd/system/postgresql-12.service.d/override.conf
  notify:
    - reload systemd
    - restart postgresql

