---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: start enable postgresql
  service:
    name: "{{ pg_service }}"
    state: started
    enabled: "{{ pg_service_enabled }}"

- name: start postgresql
  service:
    name: "{{ pg_service }}"
    state: started

- name: reload postgresql
  service:
    name: "{{ pg_service }}"
    state: reloaded

- name: restart postgresql
  service:
    name: "{{ pg_service }}"
    state: restarted

- name: stop postgresql
  service:
    name: "{{ pg_service }}"
    state: stopped
